FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Устанавливаем тулчейн сборки и библиотеки paho-mqtt и pqxx
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libpq-dev \
    libpqxx-dev \
    libpaho-mqtt-dev \
    libpaho-mqttpp-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /telemetry
COPY . .

RUN mkdir build && cmake -DBUILD_ENABLE_GOOGLE_BENCHMARK=ON -B build && cmake --build build

CMD sh -c "./build/bench"
